### PR TITLE
Add basic command usage metrics

### PR DESCRIPTION
**Pull request by AlphaKretin**
There is some refinement that could still be done here. There could be opportunities for code re-use or other consistency with logging code. Additionally, this is currently based on the code from old Bastion, which we may want to change.

### CODE REVIEW

**Review by kevinlul — COMMENTED** [review]
Okay yeah, this is a great start. I would definitely fit this class into the dependency injection system and also save the prepared statement instead of rebuilding it every time.

**Review by kevinlul — COMMENTED** [review]
Metrics#db is only async because of readFile, even though existsSync is used.

I suggest first adding metrics as a dependency of Command for tsyringe instead of having a global instance. Then convert the getDB initialization to be synchronous in the constructor — it's going to run only at startup anyway. Now the prepared statement can simply be another private property, and everything is synchronous.

**Comment by AlphaKretin** [comment]
> Metrics#db is only async because of readFile, even though existsSync is used.

exists (async) is deprecated, at least according to my IntelliSense. I've become averse to the sync fs methods due to perceptions of "best practice", but on reflection it makes sense for what will be a one-time initialisation step.

**Comment by kevinlul** [comment]
Let's further add
```ts
db.pragma('journal_mode = WAL');
```
in the initial database connection per the author's recommendation in JoshuaWise/better-sqlite3#262

**Comment by kevinlul** [comment]
Good?

**Comment by AlphaKretin** [comment]
If all the docker stuff is ready and working, and there aren't other changes to be made, then yeah, I'd think so

**Pull request merged**
