### PR TITLE
deck: Handle valid but empty input

### PR DESCRIPTION
**Pull request by AlphaKretin**

### CODE REVIEW

**Review by kevinlul — APPROVED** [review]
:(

**Comment by AlphaKretin** [comment]
We can throw in an easter egg response if you want! We've just gotta decide on what it's gonna be in that case.

**Comment by kevinlul** [comment]
- There's nothing here 👀 
- This deck is as empty as my soul, because I am a robot 🤖

**Comment by kevinlul** [comment]
Merge first, goofy later

**Pull request merged**
