### PR TITLE
Display placeholder IDs in card embed footer

### PR DESCRIPTION
**Pull request by kevinlul**
Open to feedback on what the footer should look like. This also fixes the instances of `Password: null` or `Konami ID #null` as that has unclear meaning to the layperson. However, "fake password" also isn't necessarily clear to the layperson either.

### CODE REVIEW

**Review by AlphaKretin — COMMENTED** [review]
You're right that "fake password" is a potentially confusing term. Is there a more concise way to say "temporary" or "placeholder" password? Also, I didn't know that line breaks were even allowed in footers. I'd like to see an example of how it looks. Code-wise this is 👍.

**Comment by kevinlul** [comment]
image
image

The problem is that they are permanent for these select cards _without_ passwords.

**Comment by AlphaKretin** [comment]
Right, that looks fine. 
> The problem is that they are permanent for these select cards _without_ passwords.
True. Placeholder might be the more appropriate term then, rather than temporary. But either way it's still a bit... long. A difficult tradeoff between detailed and cluttered or concise and unclear.

**Comment by kevinlul** [comment]
Placeholder ID?

**Comment by kevinlul** [comment]
Placeholder password is definitely long and funky alliteration

**Comment by AlphaKretin** [comment]
> Placeholder ID?

Hmmmmmmm I definitely like how this rolls off the tongue. It might be good to not conflate it with a password, too, even if it does serve that role in places.

**Review by AlphaKretin — APPROVED** [review]

**Pull request merged**
