### PR TITLE
Display ruby text using Discord markdown for subtext

### PR DESCRIPTION
**Pull request by kevinlul**
Per https://support.discord.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline (and https://gist.github.com/matthewzring/9f7bbfd102003963f9be7dbcf7d40e51), adding `-# ` at the start of a line causes it to appear as subtext on Discord. The font size is smaller and the colour is muted. This is exclusively Discord-flavoured markdown and does not appear in other dialects.

We use this to render ruby text for Japanese and Korean when it's available. In these cases, the embed will not have a title. The description section instead starts with the constructed ruby text of the card name as a subtext, followed by the base text of the card name, bolded and hyperlinked as if it were still the embed title. Using a markdown header is not good here as we can't get rid of the top padding on the header between the two versions of the card name. In all other cases, the behaviour is unchanged and the card name will continue to be the embed title.

Also upon request, drop Korean RR from display, as it's not relevant to native speakers.

Integration tests accounting for this change in embed title to come afterward.

### CODE REVIEW

**Comment by kevinlul** [comment]
cc: @Ice-Pendragon @myyourcaramel

**Review by AlphaKretin — APPROVED** [review]
While it's unfortunate that restrictions prevent us from using titles or headers, this is definitely the least bad option is is overall a good-looking change. Looks good on the code side too, of course.

**Comment by kevinlul** [comment]
image
image
Korean RR dropped:
image
EN unchanged: 
image

**Comment by kevinlul** [comment]
image
image
image
Rush Duel:
image

**Pull request merged**
